// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wroqkxrbsfxlyqjyvcly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyb3FreHJic2Z4bHlxanl2Y2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDU0NTEsImV4cCI6MjA3MjM4MTQ1MX0.G8ZgqyIo5N_6JkKp5snTVOrNnDuw84UYYtk5fNz-QBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});